### ISSUE TITLE
When a sample is failed the analyzer thrwos exception [Null or zero length 'values' argument.]

### ISSUE THREAD

**Issue by asankeg2000** [afranken/jmeter-analysis-maven-plugin#47]
My jtl is as follows

```
<?xml version="1.0" encoding="UTF-8"?>
<testResults version="1.2">
<sample t="81" it="0" lt="0" ct="0" ts="1481591282275" s="true" lb="TestPreperation" rc="200" rm="Number of samples in transaction : 2, number of failing samples : 0" tn="Test Preparation Activities 1-1" dt="" de="" by="0" sc="1" ec="0" ng="1" na="1" hn="WIN100">
  <responseFile class="java.lang.String"></responseFile>
</sample>
<sample t="5623" it="0" lt="0" ct="0" ts="1481591292900" s="false" lb="02_Test_TestCase" rc="200" rm="Number of samples in transaction : 19, number of failing samples : 8" tn="02_Test 1-1" dt="" de="" by="246659" sc="1" ec="1" ng="1" na="1" hn="WIN100">
  <responseFile class="java.lang.String"></responseFile>
</sample>

</testResults>
```

My Analyzer plugin is configured as below

```
			<plugin>
				<groupId>com.lazerycode.jmeter</groupId>
				<artifactId>jmeter-analysis-maven-plugin</artifactId>
				<version>1.0.6</version>
				<configuration>
					<source>${project.build.directory}/jmeter/results/top_level_table.jtl</source>
				</configuration>
				<executions>
					<execution>
						<id>create-html-report</id>
						<phase>verify</phase>
						<goals>
							<goal>analyze</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

When run the below exception thrown.

> [INFO] --- jmeter-analysis-maven-plugin:1.0.6:analyze (create-html-report) @ ccs-regression ---
> [INFO]  
> [INFO] -------------------------------------------------------
> [INFO]  A N A L Y S I N G    J M E T E R    R E S U L T S
> [INFO] -------------------------------------------------------
> [INFO]  
> [INFO] Start index.
> [INFO] End index.
> [INFO] Analysing 'top_level_table.jtl'...
> [INFO] Finished Parsing 2 entries.
> Group: Test
>   time: 20161213T120802+1100 - 20161213T120802+1100
>   total duration:       0
>   requests:             1
>   requests per second:  0
>   response duration (ms)
>     min:                81
>     average:            81
>     max:                81
>     standard deviation: 0
>     quantiles (ms)
>          10%        0
>          20%        0
>          30%        0
>          40%        0
>          50%        0
>          60%        0
>          70%        0
>          80%        0
>          90%        0
>          99%        0
>        99.9%        0
>       100.0%       81 (max. value)
>   response size (bytes)
>     total:              0
>     min:                0
>     average:            0
>     max:                0
>     standard deviation: 0
>   response status codes
>     200:                   1 (100%)
> Group: 02_Test
>   time: 20161213T120812+1100 - 20161213T120812+1100
>   total duration:       0
>   requests:             0
>   requests per second:  0
>   errors:               100%
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 10:40 min
> [INFO] Finished at: 2016-12-13T12:17:58+11:00
> [INFO] Final Memory: 30M/485M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.lazerycode.jmeter:jmeter-analysis-maven-plugin:1.0.6:analyze (create-html-report) on project ccs-regression: Error analysing: Null or zero length 'values' argument. -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.lazerycode.jmeter:jmeter-analysis-maven-plugin:1.0.6:analyze (create-html-report) on project ccs-regression: Error analysing
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.MojoExecutionException: Error analysing
> 	at com.lazerycode.jmeter.analyzer.AnalyzeMojo.execute(AnalyzeMojo.java:233)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> 	... 20 more
> Caused by: java.lang.IllegalArgumentException: Null or zero length 'values' argument.
> 	at org.jfree.data.statistics.HistogramDataset.getMinimum(HistogramDataset.java:221)
> 	at org.jfree.data.statistics.HistogramDataset.addSeries(HistogramDataset.java:136)
> 	at com.lazerycode.jmeter.analyzer.writer.ChartWriter.createResponseTimesPlot(ChartWriter.java:188)
> 	at com.lazerycode.jmeter.analyzer.writer.ChartWriter.writeCharts(ChartWriter.java:95)
> 	at com.lazerycode.jmeter.analyzer.writer.ChartWriter.write(ChartWriter.java:65)
> 	at com.lazerycode.jmeter.analyzer.ResultAnalyzer.analyze(ResultAnalyzer.java:47)
> 	at com.lazerycode.jmeter.analyzer.AnalyzeMojo.analyze(AnalyzeMojo.java:318)
> 	at com.lazerycode.jmeter.analyzer.AnalyzeMojo.execute(AnalyzeMojo.java:217)
> 	... 22 more
> [ERROR]

**Comment by raofq** [comment]
@asankeg2000  I hav encountered the same problem, has it been resolved?

**Comment by asankeg2000** [comment]
@raofq I'm not sure .. as I gave it up looking for the answer due to other priorities.

**Comment by ghenzler** [comment]
This seems to happen if there is no successful sampler data at all (played with http timeouts, I get this when the timeout is so low that not a single request is successful)
